export const GET_SEARCH_REQUEST="GET_SEARCH_REQUEST"
export const GET_SEARCH_SUCCESS="GET_SEARCH_SUCCESS"
export const GET_SEARCH_FAILURE="GET_SEARCH_FAILURE"
export const GET_VEDIO_REQUEST="GET_VEDIO_REQUEST"
export const GET_VEDIO_SUCCESS="GET_VEDIO_SUCCESS"
export const GET_VEDIO_FAILURE="GET_VEDIO_FAILURE"


