export const GET_NEWS_DATA_REQUEST = "GET_NEWS_DATA_REQUEST"
export const GET_NEWS_DATA_SUCCESS = "GET_NEWS_DATA_SUCCESS"
export const GET_NEWS_DATA_FAILURE = "GET_NEWS_DATA_FAILURE"

export const GET_CORONA_NEWS_SUCCESS = "GET_CORONA_NEWS_SUCCESS"
export const GET_INDIA_NEWS_SUCCESS = "GET_INDIA_NEWS_SUCCESS"
export const GET_TOP_STORIES_SUCCESS = "GET_TOP_STORIES_SUCCESS"