export const GET_NEWS_DATA_REQUEST = "GET_NEWS_DATA_REQUEST"
export const GET_NEWS_DATA_SUCCESS = "GET_NEWS_DATA_SUCCESS"
export const GET_NEWS_DATA_FAILURE = "GET_NEWS_DATA_FAILURE"

export const GET_ASIA_NEWS_SUCCESS = "GET_ASIA_NEWS_SUCCESS"