export const GET_NEWSDATA_REQUEST = "GET_NEWSDATA_REQUEST"
export const GET_NEWSDATA_FAILURE = "GET_NEWSDATA_FAILURE"
export const GET_NEWSDATA_SUCCESS = "GET_NEWSDATA_SUCCESS"
export const GET_SINGLE_ID_REQUEST = "GET_SINGLE_ID_REQUEST"
export const GET_SINGLE_ID_FAILURE = "GET_SINGLE_ID_FAILURE"
export const GET_SINGLE_ID_SUCCESS = "GET_SINGLE_ID_SUCCESS"

